### ISSUE TITLE
My wish to play pc games on android its ruined i cant fix this problem i tried everything 😔

### ISSUE THREAD

**Issue by balintTheDevX** [olegos2/mobox#361]
Uploading mobizen_20240415_202720.mp4…

**Comment by balintTheDevX** [comment]
> Uploading mobizen_20240415_202720.mp4…

**Comment by balintTheDevX** [comment]
Uploading mobizen_20240415_202720.mp4…

**Comment by balintTheDevX** [comment]
Check this video

**Comment by balintTheDevX** [comment]
I tried More toturials and its still not working

**Comment by balintTheDevX** [comment]
Bruh

**Comment by olegos2** [comment]
You haven't uploaded any videos... You created an issue, that says "Uploading mobizen_20240415_202720.mp4…", nice

**Comment by balintTheDevX** [comment]
Its a vide of the issue

**Comment by balintTheDevX** [comment]
Its a video

**Comment by balintTheDevX** [comment]
Of the issue

**Comment by balintTheDevX** [comment]
Uploading mobizen_20240415_202720.mp4…

**Comment by balintTheDevX** [comment]
Uploading mobizen_20240415_202720.mp4…

![Screenshot_20240415_202809_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/44baf32b-532d-4ff0-8eba-48a0e587fed9)

**Comment by balintTheDevX** [comment]
When I try to run a game its not load i tried many toturials from youtube still not load

**Comment by BiatuAutMiahn** [comment]
@olegos2 it looks like he submitted the post before the upload finishes, and he's posting multiple times within a minute. 
@balintTheDevX, spamming the issues of mobox isn't going to escalate your issue. You have provided almost zero information to work with...in another issue you mentioned MediaTek. We need to know the following to help...

- What is the model number of your device?
- What version of android are you running? (Build number?)
- What game are you trying to play?
- What steps did you take so far in attempting to play?

When experimenting with mobox I had to try different combinations of the graphics settings (dxvk, virgl, turnip+zink, wined3d) and dynarec settings to get some things to work, but just to be clear it takes a long time to figure out the right config, I've had to restart mobox like 20 times for one game alone. 

Also something to keep in mind is that there are literally 8 contributors of this project with different backgrounds, areas of expertise, and focus. Well established projects and software have a team with engineers, developers, and testers. Sometimes a few, to hundreds per area of need, per module/feature, per stage of development, (alpha, beta, release candidate, production), etc. By the time something reaches production every aspect of the software is tested and the end user experience is seamless.

**Comment by AndKmg770** [comment]
> When I try to run a game its not load i tried many toturials from youtube still not load Like when I click of a game exe it doesn't appear when I click on it not load

Can you tell us which game is it? In some games this issue had happened to me as well. Take a note of the following points.
1) Make sure all versions of Visual C++ Redistributable are installed - 2005, 2008, 2010, 2013, 2015-22 both 32 and 64 bit versions.
2) If game is not starting in performance mode then change Dynarec Settings to - 25 (Compatibility Mode)
3) Take a note of the DirectX version that the game uses. If it uses DirectX 8,9 use DXVK 1.10.3 driver. If It uses DirectX 10 you will need to use DXVK 0.96 driver. In case of Dx11, DXVK 1.10.3 can be used. 
4) Also make sure you properly install wine mono & gecko, for applications which are dependent on Dot Net. Also install Open AL.

Once again, please mention the name of the game/games that are unable to start, so that we can help you further.
And also please note that there are some games that i've tried like - Mirrors Edge 2009, Hitman Absolution etc which refuses to run in some devices (like mine) but it runs successfully in other devices. So in such cases where the games refuse to show signs of life despite following all the above steps you will just need to give up on those games (just like I did) because it definitely has something to do with the phone's GPU not supporting that particular game. So it would be a complete waste of time trying to fix games such as these. Just wait for further updates of mobox emulator and move on with other games.

PS - I am eagerly waiting for native Xinput Controller support on mobox because Input Bridge causes a lot of lag in a few games. I hope the devs will implement this soon.

**Comment by BiatuAutMiahn** [comment]
This project needs a compatibility page with game titles, devices tested, configuration used, and playability state.

**Comment by AndKmg770** [comment]
> This project needs a compatibility page with game titles, devices tested, configuration used, and playability state.

Yes, exactly. It is because there are a lot of games (mostly old games) which face compatibility issues with mobox. Maybe those games run alright on a native PC, but suppose it's not running on mobox, so it becomes difficult to understand, did I do something wrong during the game setup, do I need some extra patch files or is it mobox itself which had compatibility issues with the game.

**Comment by BiatuAutMiahn** [comment]
> > This project needs a compatibility page with game titles, devices tested, configuration used, and playability state.
> 
> Yes, exactly. It is because there are a lot of games (mostly old games) which face compatibility issues with mobox. Maybe those games run alright on a native PC, but suppose it's not running on mobox, so it becomes difficult to understand, did I do something wrong during the game setup, do I need some extra patch files or is it mobox itself which has compatibility issues with the game.

Right, I figure that the hardware that is being tested should have emphasis since mobile hardware varies more than PCs. Unlike PCs where a good 90% are x86_64 and running windows, the mobile chipsets' feature set varies alot if im not mistaken. Idk, I'd say focus on the CPU and SKU being used.
